export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_SINGLE_SUCCESS = "GET_SINGLE_SUCCESS";
export const ADD_SINGLE_SUCCESS = "ADD_SINGLE_SUCCESS";
export const ADD_QTY_SUCCESS = "ADD_QTY_SUCCESS";
